# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardWidgetLastUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('widget_name', models.CharField(max_length=128, unique=True, verbose_name='Widget name')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Last update')),
            ],
        ),
        migrations.CreateModel(
            name='DashboardWidgetSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('widget_name', models.CharField(max_length=128, verbose_name='Widget name')),
                ('setting_name', models.CharField(max_length=128, verbose_name='Setting name')),
                ('value', models.CharField(max_length=4000, verbose_name='Setting name')),
            ],
            options={
                'permissions': (('can_view_dashboard', 'Can view the dashboard'),),
            },
        ),
        migrations.AlterUniqueTogether(
            name='dashboardwidgetsettings',
            unique_together=set([('widget_name', 'setting_name')]),
        ),
    ]
